server:
  type: simple
  applicationContextPath: /
  rootPath: /service/*
  #adminContextPath: /admin # If you plan to use an admin path, you'll need to also use non-root app path
  connector:
    type: http
    port: 8080

assetsPath: /html/

database:
       driverClass: com.mysql.jdbc.Driver
       user: phonebookuser
       password: phobnebookpassword
       url: jdbc:mysql://localhost/phonebook

# use the simple server factory if you only want to run on a single port
# HEROKU NOTE - the port gets be overridden with the Heroku $PORT in the Procfile




# HEROKU NOTE - Heroku only opens a single port so can't use the usual Dropwizard app-and-admin configuration
#server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
#  applicationConnectors:
#    - type: http
#      port: 8080
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
# this requires the npn-boot library on the JVM's boot classpath
#    - type: spdy3
#      port: 8445
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
#  adminConnectors:
#    - type: http
#      port: 8081
#    - type: https
#      port: 8444
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
